version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-management-api
    container_name: task_management_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - task_network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: task_management_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - task_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: task_management_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: task_management_api
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel_user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - task_network

networks:
  task_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
